Project setup improvements
krigga/flappy-bird-server pull request #3
Opened 2023-12-12 11:50 UTC by barinbritva

* Readme for Docker setup
* Top up balance hint
* PostgreSQL to SQLite for more streighforward setup

2023-12-12 11:55 UTC, barinbritva commented on setup.sh
> +            return 0
`Y` is uppercased, let it be the default value

2023-12-12 11:55 UTC, barinbritva commented on setup.sh
> +    initialize_env_file
In case there is no `.env` file yet, let's create it

2023-12-12 11:55 UTC, barinbritva commented on src/data-source.ts
> +    migrations: [resolve(__dirname, '../migrations', '*.{ts,js}')],
I moved migrations from `src` as far it doesn't come to the result bundle

2023-12-18 17:18 UTC, thekiba requested changes

2023-12-18 17:18 UTC, thekiba commented on setup.sh
> +            return 0
Лучше запрашивать четкий ответ, потому что `./setup.sh` может перезаписать сид фразу, которая хранится в .env

2023-12-18 17:18 UTC, thekiba commented on setup.sh
> +npm install
Можешь напомнить почему мы отказались от `npm ci`? Там не ставились какие-то зависимости для windows под wsl? Можешь попробовать поэкспериментировать, чтобы это работало корректно с `npm ci`?

2023-12-18 17:18 UTC, thekiba commented on src/migrations/1700516497255-seed.ts
Миграцию с seed нужно вернуть, потому что она наполняет базу данных items для продажи. Без них не будет корректно работать покупка items

2023-12-18 17:18 UTC, thekiba commented on setup.sh
Сюда еще стоит добавить проверку на существование `.sqlite` файла, и аналогично как это сделано с `.env`, сделать ее первичную инициализацию

2023-12-18 17:18 UTC, thekiba commented on README.md
> +### Preparation
Нужно добавить про запуск `./setup.sh` для установки

2023-12-18 17:18 UTC, thekiba commented on README.md
> +// todo
Здесь нужно добавить команду `npm start` для запуска вручную, и лучше поставить Running manually выше Docker, чтобы Docker оставить для прода (если кому потребуется)

2023-12-19 09:21 UTC, barinbritva commented on setup.sh
> +npm install
`npm ci` удаляет `node_modules` перед установкой. Поэтому запуская `setup.sh` каждый раз приходиться дожидаться установки модуляей с нуля. А в Docker'е  - да, попробую вернуть `ci`

2023-12-19 10:37 UTC, barinbritva commented on README.md
> +### Preparation
Есть, третьим пунктом после создания аккаунтов пиньяты и нрока

2023-12-19 11:00 UTC, barinbritva commented on setup.sh
> +            return 0
Вернул. Сделал только `Y` строчной, чтобы не выглядело, как значение по умолчанию 😊

2023-12-19 11:01 UTC, barinbritva commented on setup.sh
> +npm install
Вернул в Докер `npm ci` - обновил `ngrok` и баг ушёл

Ссылки на баг для истории:
* https://github.com/lerna/lerna/issues/3815
* https://github.com/nrwl/nx/issues/18807

2023-12-19 11:01 UTC, barinbritva commented on src/migrations/1700516497255-seed.ts
Не заметил. Вернул

2023-12-19 11:02 UTC, barinbritva commented on setup.sh
Добавил запуск миграций, если файла нет

2023-12-19 11:03 UTC, barinbritva commented on README.md
> +// todo
Готово

2023-12-21 11:51 UTC, thekiba approved these changes

2023-12-21 11:51 UTC, merged